### ISSUE TITLE
Support for JIT?

### ISSUE THREAD

**Issue by timolins** [AndyOGo/tailwindcss-nested-groups#10]
- **I'm submitting a ...**
  [x] feature request

- **Summary**

I'd love to use this plugin with the new Just in Time mode. Is this possible? It didn't work in my  attempt.

**Comment by AndyOGo** [comment]
Thanks @timolins for your question.

Please consult tailwind itself. JIT mode is a new feature with many open bugs:
https://github.com/tailwindlabs/tailwindcss/issues?q=is%3Aissue+is%3Aopen+jit
