### ISSUE TITLE
JIT mode breaks nested groups

### ISSUE THREAD

**Issue by vafwillmann** [AndyOGo/tailwindcss-nested-groups#11]
Tailwind's JIT mode seems to break nested groups... anyone else having this issue?

**Comment by AndyOGo** [comment]
Yes, enabling JIT breaks this plugin.

#10

**Comment by MythicOrange** [comment]
> Yes, enabling JIT breaks this plugin.

JIT seems to be in tailwind's future, and this plugin is a serious boon for the average developer.
It would be nice to have a modernized version of it.

**Comment by AndyOGo** [comment]
@MythicOrange 

Indeed, JIT is in preview since tailwind v2.1+.
https://v2.tailwindcss.com/docs/just-in-time-mode

You can find a list of open JIT related bugs here:
https://github.com/tailwindlabs/tailwindcss/issues?q=is%3Aissue+is%3Aopen+jit
