### ISSUE TITLE
Make compatible with tailwindcss 3

### ISSUE THREAD

**Issue by doompadee** [AndyOGo/tailwindcss-nested-groups#12]
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request

- **Summary**
Simply updating project dependencies with `npm u` fails because of defined peer dependencies < 3. The plugin itself seems to work fine with tailwindcss 3.0

- **Other information**

npm output:
```
While resolving: 
npm ERR! Found: tailwindcss@3.0.2
npm ERR! node_modules/tailwindcss
npm ERR!   dev tailwindcss@"^3.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@">=1 <=2" from tailwindcss-nested-groups@1.2.4
npm ERR! node_modules/tailwindcss-nested-groups
npm ERR!   dev tailwindcss-nested-groups@"^1.2.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by thousandsofraccoons** [comment]
Hello, thank you for the nice plugin. I've compatibility issue also:
```
error eslint@8.5.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.16.1"
error Found incompatible module.
```

**Comment by AndyOGo** [comment]
Bumping to v3 is not ideal, as long as JIT mode breaks this plugin.

See #10 and #11

**Comment by doompadee** [comment]
Understood. It seems to work fine for me though. Not sure what problems others have. For my (simple) use case with tailwind CLI everything seems to work just fine.

**Comment by iantearle** [comment]
@doompadee how did you achieve to get this working?

**Comment by doompadee** [comment]
I simply installed with npm (have to use --force now) and adjusted the tailwind config. Nothing special.

**Comment by iantearle** [comment]
Of course. --force... stupidly forgot that. Thank you.

**Comment by MythicOrange** [comment]
> adjusted the tailwind config

Pray tell, what adjustments did you make to the config?

**Comment by doompadee** [comment]
> Pray tell, what adjustments did you make to the config?

Just the usual plugin activation:

```javascript
  plugins: [
    require('@tailwindcss/typography'),
    require("tailwindcss-nested-groups"),
    plugin(function ({ addVariant, e }) {
      addVariant('not-first', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => {
          return `.${e(`not-first${separator}${className}`)}:not(:first-child)`
        })
      })
    }),
  ],
```
I'm using nested-groups in a Hugo project and perform CSS generation via CLI:

`npx tailwindcss -i themes/artsy/assets/css/tailwind.css -o static/css/main.css --postcss --jit --watch`

Works for me with Tailwind 2 + 3.

**Comment by AndyOGo** [comment]
@doompadee 
Interesting, thx for sharing.

I have two bug reports though claiming JIT is not working with this plugin, namely #10 and #11.
Unfortunately none of these have provided clear reproduction repos.

To my knowledge the plugin API's like `addVariant` didn't change either.

**Comment by doompadee** [comment]
> Unfortunately none of these have provided clear reproduction repos.

They didn't provide any useful information at all...

Did you do any testing yourself with tailwind 3? JIT mode is stable, tailwind 3 is JIT-only! Seems logical to me to try and support it, if you want the plugin to stay relevant.

**Comment by AndyOGo** [comment]
@doompadee 

Please have a look at these examples from the [usage in the readme](https://github.com/AndyOGo/tailwindcss-nested-groups#usage), V3 is clearly broken
V3: https://play.tailwindcss.com/K1OQ7P6fpu

Versus V2: https://play.tailwindcss.com/LynJHjqDNU

> JIT mode is stable, tailwind 3 is JIT-only!

Please be aware that JIT has still open issues
https://github.com/tailwindlabs/tailwindcss/issues?q=is%3Aissue+is%3Aopen+jit
