### ISSUE TITLE
Support for Tailwind V3

### ISSUE THREAD

**Issue by SeanCassiere** [AndyOGo/tailwindcss-nested-groups#13]
- **I'm submitting a ...**
  [] bug report
  [x] feature request
  [x] question about the decisions made in the repository
  [] question about how to use this project

- **Summary**
Wanted to ask if there were any plans for supporting Tailwind 3 as the npm package is currently locked to only v1 and v2.

**Comment by AndyOGo** [comment]
Please see #10 #11 or #12
