### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by richyrb00** [AndyOGo/tailwindcss-nested-groups#14]
warning " > tailwindcss-nested-groups@1.2.4" has incorrect peer dependency "tailwindcss@>=1 <=2".

as tailwindcss has now been in version 3 for a while now could this dependency be updated within this package please?

**Comment by AndyOGo** [comment]
Tailwaind 3 has named and arbitrary groups.
Read more here:
https://tailwindcss.com/docs/hover-focus-and-other-states#differentiating-nested-groups
