### ISSUE TITLE
Module name mismatch

### ISSUE THREAD

**Issue by hognevevle** [AndyOGo/tailwindcss-nested-groups#3]
Thank you for providing this!

Just wanted to report a small issue in the readme.  There seem to be a copy/paste gone wrong, where it says to install tailwindcss-**named**-groups instead of tailwindcss-**nested**-groups.

**Comment by AndyOGo** [comment]
Thanks a lot, that is indeed wrong.
I will fix it asap.

**Comment by AndyOGo** [comment]
fix released in `v1.1.3`
https://github.com/AndyOGo/tailwindcss-nested-groups/compare/v1.1.2...v1.1.3
