### ISSUE TITLE
how to use groupLevel

### ISSUE THREAD

**Issue by akalitenya** [AndyOGo/tailwindcss-nested-groups#9]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [* ] question about how to use this project

- **Summary**
Can you please explain the purpose of "groupLevel" parameter. When we need to use it?

**Comment by AndyOGo** [comment]
This rule applies the direct child selector to scope the style to that level of nesting.

this needs to be applied as many times as levels of nesting you want to support.
